# Generated by Django 2.2.28 on 2025-01-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjobstatus',
            options={'verbose_name_plural': 'User Jobs Status'},
        ),
        migrations.AlterModelOptions(
            name='userrecords',
            options={'verbose_name_plural': 'User Records'},
        ),
    ]
