# Generated by Django 2.2.28 on 2025-01-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20250106_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecords',
            name='dob',
            field=models.DateField(default='2000-12-09'),
            preserve_default=False,
        ),
    ]
